### ISSUE TITLE
Can't get the auto-completion to work on ST3

### ISSUE THREAD

**Issue by Asuza** [austincrft/sublime-gherkin-auto-complete-plus#15]
My project doesn't have the "features" directory at the root level, so I've added the following config:

``` javascript
{
    // A collection of the directories containing the features files you would like to scan
    "feature_file_directories":
    [
      "root/subdir",
      "root/subdir/features" // also tried this
    ]
}
```

After saving the config, I switch tabs to one of my feature files and try typing various keywords (Given, When, Then, etc) but no auto-completion occurs. I'm not sure how to troubleshoot this problem. This plugin would benefit me greatly if I could get it to work. Please let me know what else I could try.

Thanks!

**Comment by austincrft** [comment]
Are your files of type `*.feature`?

**Comment by austincrft** [comment]
Also, could you try putting [this example file](https://github.com/austincrft/sublime-gherkin-auto-complete-plus/blob/master/testing/feature-files/coffee.feature) into a directory by itself and setting that up in the config? Maybe starting simpler will help diagnose the issue.

**Comment by Asuza** [comment]
All of my files are of type `*.feature`. I added the file you suggested into its own folder, "features" at the root of my project. I commented out all of my listings in the "feature_file_directories" setting and was soon prompted to add some entries.

I then updated my config to what is here:

``` javascript
{
    "feature_file_directories":
    [
        "features"
    ]
}
```

When I then type keywords into `coffee.feature`, no auto-complete shows up. I've tried typing "Given " and waiting, "Given there" and waiting, tried activating "Show Completions" from the ST3 Edit menu. Still can't see any auto completions.

**Comment by Asuza** [comment]
I've also tried restarting Sublime more than once to see if it was necessary for the changes to take effect.

**Comment by austincrft** [comment]
I have it so you have to type the first letter after `Given`. Try typing `Given t` and see if that helps.

I don't remember my exact reasoning for implementing it that way, so I'm open to changing that if it's a problem. Also, the steps get updated on file-save and the first time the view is opened.

**Comment by austincrft** [comment]
I don't remember my exact reasoning for implementing it that way, so I'm open to changing that if it's a problem. Also, the steps get updated on file-save and the first time the view is opened.

**Comment by austincrft** [comment]
Oh. It's an absolute path, not relative to the project root. That may be the problem.

**Comment by Asuza** [comment]
I really appreciate your assistance! I don't know why I'm having so much trouble getting this working.

Do the steps get updated on saving the `Gherkin Auto-Complete Plus.sublime-settings` file, or do they get updated when saving various `*.feature` files? And if so, do those files have to be in one of the directories listed in the settings?

Also, which of these paths are valid?

``` javascript
{
    "feature_file_directories":
    [
        "/home/john/dev/myproject", // Choice A?
        "/home/john/dev/myproject/features" // Choice B?
    ]
}
```

**Comment by Asuza** [comment]
I just spotted this error in console:

```
reloading Packages/User/Gherkin Auto-Complete Plus.sublime-settings
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 264, in on_post_save_async
    callback.on_post_save_async(v)
  File "gherkin_event_listener in /home/john/.config/sublime-text-3/Installed Packages/Gherkin Auto-Complete Plus.sublime-package", line 79, in on_post_save_async
  File "gherkin_event_listener in /home/john/.config/sublime-text-3/Installed Packages/Gherkin Auto-Complete Plus.sublime-package", line 103, in _is_gherkin_scope
  File "/opt/sublime_text/sublime.py", line 513, in __getitem__
    raise IndexError()
IndexError
```

I don't know exactly what triggered it, but it looks like I'm finally seeing some auto-complete suggestions!

**Comment by austincrft** [comment]
No problem at all! 😄

Choice B should work, assuming your feature files are directly under the `features` directory.

They get updates on save of a `*.feature` file using the `Gherkin` syntax provided with this package.

**Comment by Asuza** [comment]
I'm glad you mentioned that you have to use the Gherkin syntax highlighting. I've created my own syntax for Gherkin because I didn't like any of the syntaxes I could find, so none of my files worked with your auto-complete plug-in. Is there a reason for limiting it to the `Gherkin` syntax?

**Comment by austincrft** [comment]
Really, I just didn't want my package to be intrusive. I also wanted to take advantage of the Sublime Text scopes, which allows me to do things like not offer suggestions in a commented line. I also made the (obviously incorrect) assumption that people would just use the bundled syntax.

If it helps, I'd be happy to add a configuration option for scope. This way you'd be able to choose which scopes offer suggestions.

**Comment by Asuza** [comment]
The problem with the bundled tmLanguage file is that it highlights things it shouldn't, and doesn't differentiate things it should (at least when it comes to coloring... not sure about scopes). It looks like it was copied over from a Ruby tmLanguage file.

Here's an example of my syntax highlighting as it is currently:
![Syntax Highlighting Example](http://i.imgur.com/1jxny93.png)
in the "Monokai Phoenix" theme.

**Comment by Asuza** [comment]
In terms of adding configuration options, I say the more the better! After our discussion yesterday, I modified the check for gherkin syntax to instead check that the view is a feature file. This is what I added if you want to include that as a config option:

``` python
    def _is_feature_file(self, view):
        """ Validates that user is in a feature file

        :param sublime.View view: the sublime view

        :rtype: bool
        """
        file_name = view.file_name()

        if (file_name is None):
            return False
        else
            return file_name.find(".feature", -8) > -1
```

**Comment by austincrft** [comment]
I was thinking more along the lines of this

``` python
def _is_valid_scope(self, view):
    """ Validates that user is in valid scope

    :param sublime.View view: the sublime view
    :rtype: bool
    """
    location = view.sel()[0].end()
    # PREVIOUS LINE: return view.match_selector(location, "text.gherkin.feature - comment")
    return view.match_selector(location, scope_from_config)
```

And then the config option would be defaulted like so

``` javascript
{
    // The scope where you will receive auto-complete suggestions
    "scope_for_suggestions": "text.gherkin.feature - comment",

    // other settings removed for brevity
}
```

And then you'd just override that with your scope-selector.
Thoughts?

**Comment by Asuza** [comment]
I think both would be useful for different reasons. For one, I don't think most people that use Sublime understand scopes, so having the option is fine, especially if there's an explanation on how to use it. The `_is_feature_file` I posted would probably be ideal for using in the `on_post_save_async` method, here:

``` python
    def on_post_save_async(self, view):
        if self._is_feature_file(view):
            self._update_steps()
```

That way the step catalog is updated regardless of the syntax used.

**Comment by austincrft** [comment]
That's a valid point. The average user probably doesn't understand or care about scopes. I just don't want to give auto-complete suggestions in commented lines.

Now that I think about it, it may just work by default since I'm checking the first word of the line to filter suggestions.

**Comment by austincrft** [comment]
I can make these changes, or you can fork, send a PR, and become a contributor. :smile:
Your choice.

**Comment by austincrft** [comment]
I'm going to close this. I opened #17 as an enhancement. Feel free to chime in there.

**Comment by visaHB** [comment]
Hi, I hv installed gherkin autocomplete plus using package installer in sublime text 3, though I have configured my file path as indicated and the syntax has also been set to gherkin, I am not able to see any auto complete suggestions. My files are of the *.feature and when I type something like `Given user` there is no auto complete suggestions. Is there anything else i should do? My Gherkin Auto-Complete Plus.sublime-settings file looks something like this: 
`{
    // A collection of the directories containing the features files you would like to scan
    "feature_file_directories":
    [
      "/Users/username/Documents/project/test/features"
    ],
    "logging_level": "error"
}`

There is nothing that appears on the console of sublime text, so I am really not sure what is the issue that is preventing me from using this plugin, hope you can assist. Hv been cracking my head on this for a couple of days

**Comment by austincrft** [comment]
Are you using Windows? You'll need to use the fully qualified path l with double backslashes because `\` is an escape character in JSON. Like so:
`C:\\path\\to\\feature\\directory\\`

**Comment by visaHB** [comment]
Nope I am using a mac computer

**Comment by austincrft** [comment]
Could you set your `logging_level` to `debug`, then try again and copy what you get in the sublime console?

**Comment by visaHB** [comment]
I believe when you mean change the log level to debug it would be the one on the auto complete user settings and when I do, I don't see any thing on the console. There is nothing that is shown on the sublime text console. When I click on control+space, i see no auto complete suggestion.

**Comment by austincrft** [comment]
In the directory `/Users/username/Documents/project/test/features` create a file named `test.feature` containing the following text:

``` gherkin
Feature: Coffee Testing

  Scenario: Buy first Coffee
      Given there is a coffee named "Sublime"
      And the coffee costs 1.50 dollars
      When I give the cashier 2 dollars
      And I say 'Good Morning!'
      Then I should receive the <AMAZING> coffee
      And I should receive the <input> coffee
      And I should receive 0.50 in change
```

Open the saved `test.feature` file in Sublime Text. After the last line in the scenario, type the following:

``` gherkin
And I
```

You should receive auto-complete suggestions for the following lines:

``` gherkin
And I should receive the <input> coffee
And I should receive 0.50 in change
```
