### ISSUE TITLE
Must type first character after keyword to get suggestions

### ISSUE THREAD

**Issue by austincrft** [austincrft/sublime-gherkin-auto-complete-plus#16]
I'm assuming this was unintentional because there's a comment in the code that says:
`If only keyword is typed, provide all steps for keyword`

**Comment by Asuza** [comment]
Would it be possible to filter the list of suggestions as you type? I don't know if that counts as part of this auto-complete bug or it would be considered a new feature.

**Comment by austincrft** [comment]
That should already be implemented. If you have two steps

``` gherkin
Given the following step
And some other step
```

 And you type

``` gherkin
Given t
```

You should only see the top step in the suggestions.

**Comment by Asuza** [comment]
I mean when I have the steps:

``` gherkin
When I attack the enemy
When I attack a friendly
When I run away
```

If I then type `When I attack`, the list has vanished. In this case I can't filter my list. Typing `When I` won't limit anything.

**Comment by austincrft** [comment]
But if you type 

``` gherkin
When I attack t
```

does it limit it?

It should be doing it currently, but I agree that the auto-complete shutting at the last character is annoying. It's because I'm doing word-based filtering. Maybe there's a fuzzy-search solution that could be implemented.

**Comment by Asuza** [comment]
Oh, sorry. You're right. It is being limited. I think the fact that it was vanishing when I hit <kbd>Space</kbd> was throwing me off. I think the vanishing issue would be a completely separate bug.

**Comment by austincrft** [comment]
I agree. You can create that issue if you'd like.

**Comment by austincrft** [comment]
Identical to #20
