### ISSUE TITLE
Auto-complete list vanishes when typing the space key

### ISSUE THREAD

**Issue by Asuza** [austincrft/sublime-gherkin-auto-complete-plus#20]
The auto-complete list appears to vanish each time you type <kbd>Space</kbd>. I don't know if this is potentially a Sublime limitation or not, since most auto-complete lists I've seen only contain one word and not a phrase.

**Comment by austincrft** [comment]
Yeah, the <kbd>space</kbd> key is actually hard-coded in Sublime Text to commit the highlighted auto-complete entry. I had to do some semi-hacky stuff to even get around that and it took forever to figure out. I think it's unlikely that I'll be able to come up with a fix for this.

**Comment by austincrft** [comment]
Now that I think about it, that's why it's necessary to type the first letter after the keyword (or any word, for that matter). So this and #16 are identical issues.

**Comment by austincrft** [comment]
I'm going to close this as `wontfix`. Because I think this will be near-impossible unless there are changes to how Sublime Text handles <kbd>space</kbd>.

**Comment by Asuza** [comment]
@austincrft, Sublime Text 3 just added a new API: "Added View.is_auto_complete_visible()". Do you think that would make any difference in whether this ticket is possible?

**Comment by austincrft** [comment]
If I had to guess, probably not. I'll look into it, though. Re-opening so I remember to research.

**Comment by austincrft** [comment]
Did a little research here. It doesn't look like the is change to the view API will help here, sorry.
