### ISSUE TITLE
How do you run the unit tests?

### ISSUE THREAD

**Issue by Asuza** [austincrft/sublime-gherkin-auto-complete-plus#22]
I see that some unit tests appear to exist, but running the command from the travis file (`python -m unittest`) doesn't seem to do anything.

**Comment by austincrft** [comment]
if you're in the root directory, that call should work.

`python3 -m unittest` if you have python2 installed.

**Comment by Asuza** [comment]
Ah-ha! That was my problem. I guess it defaults to Python 2. Using `python3` made it show that some tests were run.

**Comment by austincrft** [comment]
Great. I should probably follow the standard `python3 setup.py test` call to run the tests, but it annoys me that it creates a `*.egg-info` folder every time when I don't plan on using the python egg stuff.

**Comment by austincrft** [comment]
Closing this because you got them to run.
