### ISSUE TITLE
Ability to see all of the available steps at once

### ISSUE THREAD

**Issue by Asuza** [austincrft/sublime-gherkin-auto-complete-plus#23]
It would be really cool hit a keyboard shortcut that shows a list of all the available steps, similar to how the Command Palette works.

A use case is that I know I have a `Then` step to check if the last step had an error thrown, and I believe I had the word "error" in the step, but I can't figure out what it was by using the existing auto-complete for steps in its current state.

A few other plugins have a similar feature for getting a list of linting errors, etc. It would be really cool to have!

**Comment by austincrft** [comment]
Great idea, I like it.

**Comment by austincrft** [comment]
I have a basic working copy of this on [branch feat/23](https://github.com/austincrft/sublime-gherkin-auto-complete-plus/tree/feat/23) if you want to check it out. Sometime this week I'm going to try to tidy this up and make a gif of the feature.

**Comment by Asuza** [comment]
Very cool! I look forward to giving it a spin as soon as I get the chance.

**Comment by Asuza** [comment]
It looks like it's nearly done! It lists a lot of steps (I can't confirm whether it's all that I have or not), but it never seems to insert the result in the list that I select. I tried choosing various steps (Given, When, Then) but none of them inserted the step I picked.

It _always_ seems to pick a Then step no matter what first word of the sentence is.

**Comment by austincrft** [comment]
Ah, my bad. I was goofing up on the sorting. Just pushed some changes that should fix that.

**Comment by Asuza** [comment]
@austincrft, it's working now.
![It's so beautiful.](http://cdn.meme.am/instances/61317909.jpg)

**Comment by austincrft** [comment]
Haha! :smile: Glad you like it. I'll try to have this finished up sometime this week.

**Comment by austincrft** [comment]
Just merged this in. I'm going to make some other changes and then draft a new release.
