### ISSUE TITLE
Does the tool only support sublime text 3?

### ISSUE THREAD

**Issue by EstherTsai** [austincrft/sublime-gherkin-auto-complete-plus#33]
Is it possible to support sublime text 2 ?

**Comment by austincrft** [comment]
The tool only supports Sublime Text 3, as stated in the README. It's possible, but I don't like writing in Python 2 and I don't want to maintain a branch for each version.

Why not use Sublime Text 3?

**Comment by austincrft** [comment]
Closing this. Will re-open if you think there is more of a discussion to be had.
