### ISSUE TITLE
''Error trying to parse settings'' after trying to save ''Settings-User''

### ISSUE THREAD

**Issue by Mojoejoe** [austincrft/sublime-gherkin-auto-complete-plus#34]
After downloading your plugin, I have followed the step ''Preferences -> Package Settings -> Gherkin Auto-Complete Plus -> Settings - User'' and copied your text in it. I have set projet folder address to ''/Users/username/Documents/project'' where all my *.feature files are. But when I try to save settings, I get a parsing error
![error](https://cloud.githubusercontent.com/assets/10675524/14524775/41dc1a3a-023a-11e6-9249-67cbc49b6aa4.png)

How to solve this problem ?

Note, I have Windows 10.

**Comment by Mojoejoe** [comment]
I have solved 'parse error' problem. I used wrong '/' and I have corrected the path. It is working now.
However, auto-complete seems to crash sometimes. It works for some time, and suddenly it stops working. I have tried exit / entering Sublime, but this doesn't fix it.
=> this happened after I saved a file.

Another question: When I open new Sublime file, it doesn't highlight Given/When/Then keywords, and auto completion doesn't work. It was only working in already saved files from Notepad++. Do you know what seems to be the problem ?

**Comment by austincrft** [comment]
You shouldn't have to configure any settings at all unless you need to specify _additional_ directories not open in Sublime Text. As for the auto-complete "crashing sometimes", could you verify that you are not experiencing the issue in #20?

When you open a new file in Sublime Text, the syntax is set to 'Plain Text' (you can see what syntax is being used in the bottom right corner of the window). The Gherkin syntax and auto-complete will not activate until you save the file with the extension `.feature`.

**Comment by austincrft** [comment]
I'll leave this open for a few more days, then close it if I hear nothing back. Please let me know if you have any more questions. :smile:

**Comment by Mojoejoe** [comment]
Sorry, but I haven't solve the problem. 
I have uninstalled sublime & your package, and installed it again. I didn't change the settings, but auto-complete still doesn't work (yes, I have opened a folder where all the files are *.feature) . I have found on forums that other people have reported after saving the file, auto-complete stops working (I don't know if this was the case or not)
I have tried other auto-complete plugin, and he will do. Shame though, because I have seen for brief time (about 1-2h) how you plugin is working. :/

Thx for the syntax explanation, that helped a lot !

**Comment by Mojoejoe** [comment]
Also I have read the issue #20 (that wasn't the case either)

**Comment by austincrft** [comment]
To diagnose the issue, set the logging level to `DEBUG` in the package settings like so:

``` javascript
{
    "logging_level": "DEBUG"
}
```

Then open the Sublime Text console from the menu via `View -> Show Console`. Now you should see debug information output to the console from my package when using the auto-complete.

Can you paste the output here?

**Comment by austincrft** [comment]
Ever have any luck deducing the issue? I'd love to help.

**Comment by austincrft** [comment]
Closing this. Let me know if you run into this again and I'll help reproduce.
