### ISSUE TITLE
Click enter button to finish the auto-completion will make the text disappear

### ISSUE THREAD

**Issue by Milesyan** [austincrft/sublime-gherkin-auto-complete-plus#38]
This is the end of the auto completion and then I click enter to finish it.
<img width="761" alt="screen shot 2016-04-28 at 7 12 36 pm" src="https://cloud.githubusercontent.com/assets/15189087/14884091/1f4b5238-0d75-11e6-8c45-59be64fc7686.png">

Result>> Only the last word is left after I click enter 
<img width="488" alt="screen shot 2016-04-28 at 7 12 40 pm" src="https://cloud.githubusercontent.com/assets/15189087/14884078/072769b2-0d75-11e6-8f21-8848270df3d6.png">

**Comment by austincrft** [comment]
Use <kbd>Tab</kbd> to complete it.

**Comment by Milesyan** [comment]
It is the same behaviour as Enter when I use Tab to complete it.
Is there some configuration wrong with my sublime?

I can use command+enter to complete it but it's not a very friendly experience.

**Comment by austincrft** [comment]
That would be my guess. Would you try it again with default user settings?

**Comment by Milesyan** [comment]
I delete all my user's settings and it is still the same.
The problem is when the auto-complete is done, the last word is still highlighted. 
And then click enter or tab button will make the whole sentence replaced by the last word.
<img width="828" alt="screen shot 2016-05-01 at 1 41 17 am" src="https://cloud.githubusercontent.com/assets/15189087/14937651/f2495d7a-0f40-11e6-933e-82734c517005.png">

**Comment by austincrft** [comment]
Ah, that could very well be a bug on my part. I will look into this. In the mean-time, you could set `"auto_complete_commit_on_tab": true` in your User settings, so that pressing <kbd>Enter</kbd> won't commit the auto-complete entry.

If you read the comment on this property, it's actually the suggested setting, not sure why it isn't the default.

**Comment by Milesyan** [comment]
Thanks, useing tab as auto-complete works fine for me :)
