### ISSUE TITLE
Question: how to configure indent space count?

### ISSUE THREAD

**Issue by xywang68** [austincrft/sublime-gherkin-auto-complete-plus#39]
Thanks for developing this plug-in, and I enjoy using it.
Out of box the Scenario template indent space count is 4, and I want to set it to 2, how do set this?
Thank you.

**Comment by austincrft** [comment]
In Sublime Text, you can specify Syntax-specific settings by going to `Preferences -> Settings - More -> Syntax Specific - User`.

It should open up a file with a path like this `Packages/User/<syntax>.sublime-settings`. The one that you're wanting is the `tab_size` setting. It'll look like this:

``` json
{
    "tab_size": 2
}
```

**Comment by xywang68** [comment]
Thank you.
