### ISSUE TITLE
Unable to see all steps

### ISSUE THREAD

**Issue by lruggiero** [austincrft/sublime-gherkin-auto-complete-plus#41]
I have to context files for my projects, I've already configured the paths to it and the auto-complete display few phrases of both projects, but not all.
I compared some of the phrases that are being displayed with the one and they look pretty much the same.
BTW, I am using behat
Ex:
``` php
//Not displayed:
/**
* @Then I should see page title :arg1
*/
public function iShouldSeePageTitle($arg1){
	//code
}

//Displayed on auto-complete:
/**
 * @Given I go to booking page with :arg1 and :arg2 as checkin and checkout dates
 */
public function iGoToBookingPageWithAndAsCheckinAndCheckoutDates($arg1, $arg2){
    //code
}
```

**Comment by austincrft** [comment]
What does your `*.feature` file look like? The actual PHP implementation of the files are not parsed for steps.

**Comment by lruggiero** [comment]
Sorry for the late reply, I was not in the office in the last days.

I believe it was a misunderstanding, I thought it parsed the implementation.
Thanks a lot for the reply

**Comment by austincrft** [comment]
Glad I could clear it up for you. :smile: Gonna close this.
